version: '3'
services:
  warpgate:
    image: ghcr.io/warp-tech/warpgate
    container_name: warpgate
    ports:
      - 2222:2222
      - 8888:8888
      - 33306:33306
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    labels:
      caddy: warpgate.gridexx.fr
      caddy.reverse_proxy: "{{upstreams https 8888}}"
      caddy.reverse_proxy.transport: http
      caddy.reverse_proxy.transport.tls: ""
      caddy.reverse_proxy.transport.tls_insecure_skip_verify: ""
      # caddy.1: ${WARP_GATE_DOMAIN}
      # caddy.1.reverse_proxy: "{{upstreams 2222}}"*
    networks:
      - caddy


  caddy:
    image: lucaslorentz/caddy-docker-proxy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
      - WARPGATE_DOMAIN=${WARPGATE_DOMAIN}
    networks:
      - caddy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
